baseURL = 'https://example.org/'
languageCode = 'en-us'
title = '中国酒都'
theme = 'ananke'
publishDir = "docs"
[markuppu]
defaultMarkdownHandler = "goldmark"
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true